name: CI

on:
  push:
    branches:
      [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Python setup
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pyTelegramBotAPI
    
    - name: Linter check (pylint)
      run: |
        find . -name '*.py' -exec pylint {} \;

    - name: Docker image Builder
      env:
        API: ${{ secrets.API_KEY }}
      run: docker build . --file Dockerfile --tag py-docker
