name: CI

on:
  push:
    branches:
      [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Python setup
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pyTelegramBotAPI
    
    - name: Linter check (pylint)
      run: |
        find . -name '*.py' -exec pylint {} \;

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker image Builder
        env:
          API: ${{ secrets.API_KEY }}
        run: docker build . --file Dockerfile --tag py-docker

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build, docker
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: nomoreactimel/telegram_bot_missing_semester
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
